name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository universe
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          git \
          python3 \
          python3-dev \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          libgstreamer1.0 \
          gstreamer1.0-tools \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          libpq-dev \
          openjdk-11-jdk \
          autoconf \
          automake \
          libtool \
          pkg-config \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo-dev \
          cmake \
          wget \
          unzip \
          libffi-dev \
          libssl-dev
        
        # Install libtool and its dependencies
        sudo apt-get install -y libltdl-dev
        sudo apt-get install -y libtool-bin
        
        # Verify git installation
        git --version
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade Cython==0.29.33
        pip install buildozer
        pip install -r requirements.txt
    
    - name: Clean up previous Android SDK installation
      run: |
        rm -rf ~/.buildozer/android/platform/android-sdk
        rm -rf ~/.buildozer/android/platform/android-ndk*
        rm -rf ~/.buildozer/android/platform/cmdline-tools
    
    - name: Install Android SDK and NDK
      run: |
        mkdir -p ~/.buildozer/android/platform
        cd ~/.buildozer/android/platform
        
        # Download and install Android Command Line Tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-9477386_latest.zip
        mkdir -p cmdline-tools/latest
        mv cmdline-tools/* cmdline-tools/latest/ 2>/dev/null || true
        
        # Set up environment variables
        export ANDROID_HOME=~/.buildozer/android/platform
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
        
        # Accept licenses and install required packages
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0"
        
        # Download and install Android NDK
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip android-ndk-r25b-linux.zip
        
        # Create symbolic links for buildozer
        ln -sf $ANDROID_HOME/android-sdk android-sdk
        ln -sf $ANDROID_HOME/android-ndk-r25b android-ndk
    
    - name: Configure buildozer
      run: |
        # Create buildozer.spec if it doesn't exist
        if [ ! -f "buildozer.spec" ]; then
          buildozer init
        fi
        
        # Update buildozer.spec with correct paths
        sed -i 's|android.sdk_path = .*|android.sdk_path = ~/.buildozer/android/platform/android-sdk|' buildozer.spec
        sed -i 's|android.ndk_path = .*|android.ndk_path = ~/.buildozer/android/platform/android-ndk|' buildozer.spec
        sed -i 's|android.api = .*|android.api = 31|' buildozer.spec
        sed -i 's|android.minapi = .*|android.minapi = 21|' buildozer.spec
        sed -i 's|android.ndk = .*|android.ndk = 25b|' buildozer.spec
    
    - name: Build APK
      env:
        TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
        ANDROID_HOME: ~/.buildozer/android/platform
        ANDROID_SDK_ROOT: ~/.buildozer/android/platform/android-sdk
        ANDROID_NDK_HOME: ~/.buildozer/android/platform/android-ndk
        PATH: $PATH:$ANDROID_HOME/cmdline-tools/latest/bin:/usr/bin
        LIBTOOLIZE: /usr/bin/libtoolize
        ACLOCAL: /usr/bin/aclocal
        AUTOMAKE: /usr/bin/automake
        AUTOCONF: /usr/bin/autoconf
      run: |
        which git
        git --version
        buildozer android debug
    
    - name: Check for APK
      run: |
        if [ ! -f "bin/*.apk" ]; then
          echo "APK file not found!"
          ls -la bin/
          exit 1
        fi
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk 