name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository universe
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          git \
          python3 \
          python3-dev \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          libgstreamer1.0 \
          gstreamer1.0-tools \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          libpq-dev \
          openjdk-11-jdk \
          autoconf \
          automake \
          libtool \
          pkg-config \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo-dev \
          cmake \
          wget \
          unzip \
          libffi-dev \
          libssl-dev
        
        # Install libtool and its dependencies
        sudo apt-get install -y libltdl-dev
        sudo apt-get install -y libtool-bin
        
        # Verify git installation
        git --version
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade Cython==0.29.33
        pip install buildozer
        pip install -r requirements.txt
    
    - name: Prepare buildozer configuration
      run: |
        # Create buildozer.spec if it doesn't exist
        if [ ! -f "buildozer.spec" ]; then
          buildozer init
        fi
        
        # Update buildozer.spec
        sed -i 's|android.api = .*|android.api = 31|' buildozer.spec
        sed -i 's|android.minapi = .*|android.minapi = 21|' buildozer.spec
        sed -i 's|android.ndk = .*|android.ndk = 25b|' buildozer.spec
        
        # Explicitly set requirements
        if ! grep -q "requirements =" buildozer.spec; then
          echo "requirements = python3,kivy,pillow,streamlit,together" >> buildozer.spec
        else
          sed -i 's|requirements = .*|requirements = python3,kivy,pillow,streamlit,together|' buildozer.spec
        fi
        
        # Set app title and package name
        sed -i 's|title = .*|title = Bangalore Food Finder|' buildozer.spec
        sed -i 's|package.name = .*|package.name = foodfinder|' buildozer.spec
        
        # Set source.dir
        sed -i 's|source.dir = .*|source.dir = .|' buildozer.spec
        
        # Set the main file
        sed -i 's|source.include_exts = .*|source.include_exts = py,png,jpg,kv,atlas,json|' buildozer.spec
        
        # Check if main.py exists, if not create it
        if [ ! -f "main.py" ]; then
          cp food_app.py main.py
        fi
    
    - name: Build APK
      env:
        TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
        ANDROID_HOME: ~/.buildozer/android/platform
        PATH: $PATH:$ANDROID_HOME/cmdline-tools/latest/bin:/usr/bin
        LIBTOOLIZE: /usr/bin/libtoolize
        ACLOCAL: /usr/bin/aclocal
        AUTOMAKE: /usr/bin/automake
        AUTOCONF: /usr/bin/autoconf
      run: |
        which git
        git --version
        
        # Let buildozer handle the SDK and NDK installation
        buildozer android debug
    
    - name: Check for APK
      run: |
        if [ -z "$(find bin -name '*.apk' 2>/dev/null)" ]; then
          echo "APK file not found!"
          ls -la bin/ || echo "bin directory does not exist"
          exit 1
        else
          echo "APK file found:"
          find bin -name "*.apk"
        fi
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk 